-- Run this once in pgAdmin or psql after creating the brainos database.
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255),
  role VARCHAR(30) NOT NULL DEFAULT 'USER',
  provider VARCHAR(30) NOT NULL DEFAULT 'LOCAL',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alarms (
  alarm_id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(120) NOT NULL DEFAULT 'Wake mission',
  alarm_time TIME NOT NULL,
  alarm_type VARCHAR(30) NOT NULL DEFAULT 'DAILY',
  repeat_days VARCHAR(50),
  difficulty VARCHAR(30) NOT NULL DEFAULT 'MEDIUM',
  sound VARCHAR(80) NOT NULL DEFAULT 'Neural Dawn',
  vibration BOOLEAN NOT NULL DEFAULT TRUE,
  snooze_minutes INTEGER NOT NULL DEFAULT 5 CHECK (snooze_minutes BETWEEN 0 AND 30),
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
