import { useEffect, useState } from "react";
import NeuralCore from "../components/NeuralCore";

const API = import.meta.env.VITE_API_URL || "http://localhost:8000";
const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("brainos_token")}` });
const nav = ["Command", "Alarms", "Challenges", "Analytics", "Settings"];

export default function Dashboard({ onSignOut }) {
  const [view, setView] = useState("Command"), [profile, setProfile] = useState(null), [alarms, setAlarms] = useState([]), [analytics, setAnalytics] = useState(null), [notice, setNotice] = useState("");
  const load = async () => { try { const [p, a, x] = await Promise.all([fetch(`${API}/profile`, { headers: headers() }), fetch(`${API}/alarms`, { headers: headers() }), fetch(`${API}/analytics`, { headers: headers() })]); if ([p,a,x].some((r) => r.status === 401)) return onSignOut(); setProfile(await p.json()); setAlarms(await a.json()); setAnalytics(await x.json()); } catch { setNotice("BrainOS API is unavailable. Keep the backend terminal running."); } };
  useEffect(() => { load(); }, []);
  const createAlarm = async (data) => { const r = await fetch(`${API}/alarm`, { method: "POST", headers: headers(), body: JSON.stringify(data) }); if (!r.ok) return setNotice("Could not create the alarm."); setNotice("Alarm synchronized to your wake plan."); load(); };
  const removeAlarm = async (id) => { await fetch(`${API}/alarm/${id}`, { method: "DELETE", headers: headers() }); load(); };
  const startMission = async (type) => { const r = await fetch(`${API}/mission`, { method: "POST", headers: headers(), body: JSON.stringify({ challenge_type: type }) }); if (r.ok) { setNotice(`${type} mission activated — +180 XP awaits.`); setView("Challenges"); } };
  return <main className="dashboard-shell"><div className="star-field" />
    <nav className="dash-nav"><div className="wordmark"><i /> BRAIN<span>OS</span></div><div className="nav-links">{nav.map((item) => <button key={item} className={view === item ? "active" : ""} onClick={() => setView(item)}>{item}</button>)}</div><div className="nav-status"><b /> ONLINE</div><button className="avatar" onClick={onSignOut} title="Sign out">{profile?.name?.[0] || "P"}</button></nav>
    {notice && <div className="toast">{notice}<button onClick={() => setNotice("")}>×</button></div>}
    {view === "Command" && <Command profile={profile} alarms={alarms} analytics={analytics} startMission={startMission} goAlarms={() => setView("Alarms")} />}
    {view === "Alarms" && <Alarms alarms={alarms} createAlarm={createAlarm} removeAlarm={removeAlarm} />}
    {view === "Challenges" && <Challenges startMission={startMission} />}
    {view === "Analytics" && <Analytics data={analytics} />}
    {view === "Settings" && <Settings profile={profile} setNotice={setNotice} updateProfile={setProfile} />}
  </main>;
}
function Command({ profile, alarms, analytics, startMission, goAlarms }) { const score = analytics?.focus_score || 74; return <><section className="command-hero"><div className="hero-copy"><p className="eyebrow">COGNITIVE COMMAND CENTER</p><h1>Good morning,<br /><em>{profile?.name || "Explorer"}.</em></h1><p>Restored systems detected. Your mind is moving with clarity today.</p><button className="quiet-button" onClick={goAlarms}>Manage wake plan <span>→</span></button></div><div className="hero-core"><NeuralCore /><div className="core-caption"><b>{score}</b><span>COGNITIVE<br />READINESS</span></div></div><div className="hero-metrics"><span>ACTIVE ALARMS <b>{alarms.length}</b></span><span>FOCUS WINDOW <b>09:30—11:20</b></span></div></section><section className="dashboard-grid"><article className="mission-card"><div><p className="eyebrow">TODAY'S WAKE MISSION</p><h2>Beat the first<br />alarm pulse.</h2><p className="mission-copy">Complete a pattern challenge within 90 seconds to lock in your wake state.</p></div><div className="mission-bottom"><span><b>+ 180</b> XP reward</span><button onClick={() => startMission("PATTERN")}>Start mission <b>→</b></button></div></article><article className="assistant-card"><div className="assistant-mark">✦</div><p className="eyebrow">BRAINOS ASSISTANT</p><h3>“Your deep sleep rose <em>18%</em> last night.”</h3><p>Small shift, real signal. Try keeping your 23:10 wind-down tonight.</p></article><Stats analytics={analytics} /></section></>; }
function Stats({ analytics }) { const stats = [{ label: "Brain energy", value: analytics?.focus_score || 74, color: "cyan" }, { label: "Sleep battery", value: analytics?.sleep_score || 72, color: "violet" }, { label: "Habit orbit", value: analytics?.habit_score || 68, color: "lime" }]; return <section className="stats-row">{stats.map((s) => <article className={`stat-card ${s.color}`} key={s.label}><p>{s.label}</p><div><b>{s.value}</b><span>%</span></div><small>Measured from your recent rhythm</small><div className="stat-line"><i style={{ width: `${s.value}%` }} /></div></article>)}</section>; }
function Alarms({ alarms, createAlarm, removeAlarm }) { const [form, setForm] = useState({ alarm_time: "07:00", repeat_days: "Mon,Tue,Wed,Thu,Fri", difficulty: "MEDIUM" }); return <section className="module-shell"><div className="module-heading"><p className="eyebrow">WAKE ORCHESTRATION</p><h1>Alarm <em>lab.</em></h1><p>Create a deliberate wake signal and attach a challenge to it.</p></div><div className="alarm-layout"><form className="module-card alarm-form" onSubmit={(e) => { e.preventDefault(); createAlarm(form); }}><h2>New wake signal</h2><label>WAKE TIME<input type="time" value={form.alarm_time} onChange={(e) => setForm({ ...form, alarm_time: e.target.value })} /></label><label>REPEAT DAYS<input value={form.repeat_days} onChange={(e) => setForm({ ...form, repeat_days: e.target.value })} placeholder="Mon,Tue..." /></label><label>MISSION DIFFICULTY<select value={form.difficulty} onChange={(e) => setForm({ ...form, difficulty: e.target.value })}><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><button className="primary-button">SYNCHRONIZE ALARM <span>→</span></button></form><div className="alarm-list">{alarms.length ? alarms.map((a) => <article className="alarm-row" key={a.alarm_id}><div><b>{String(a.alarm_time).slice(0,5)}</b><span>{a.repeat_days || "One time"} · {a.difficulty}</span></div><button onClick={() => removeAlarm(a.alarm_id)}>Delete</button></article>) : <div className="empty-state">No wake signals yet. Create your first one.</div>}</div></div></section>; }
function Challenges({ startMission }) { const tasks = [["MEMORY", "Memory matrix", "Recall the active pattern."], ["MATH", "Quick calculation", "Solve before your alarm fades."], ["PATTERN", "Signal sequence", "Match the neural sequence."], ["REACTION", "Reaction test", "Respond to the pulse."]]; return <section className="module-shell"><div className="module-heading"><p className="eyebrow">COGNITIVE CHALLENGES</p><h1>Earn your <em>morning.</em></h1><p>Each challenge is built to break through sleep inertia.</p></div><div className="challenge-grid">{tasks.map(([type, title, copy], i) => <article className="challenge-card" key={type}><span>0{i+1}</span><h2>{title}</h2><p>{copy}</p><button onClick={() => startMission(type)}>Activate <b>→</b></button></article>)}</div></section>; }
function Analytics({ data }) { const history = data?.history || [56,63,59,71,67,82,74]; return <section className="module-shell"><div className="module-heading"><p className="eyebrow">COGNITIVE INSIGHTS</p><h1>Your rhythm,<br /><em>decoded.</em></h1></div><Stats analytics={data} /><article className="module-card full-chart"><div><p className="eyebrow">SLEEP QUALITY · 7 DAYS</p><h2>Recovery is trending upward.</h2></div><div className="rhythm-chart">{history.map((v, i) => <span key={i} className={i === history.length - 1 ? "active" : ""} style={{ height: `${v}%` }} />)}</div></article></section>; }
function Settings({ profile, updateProfile, setNotice }) { const [name, setName] = useState(profile?.name || ""); useEffect(() => setName(profile?.name || ""), [profile]); const save = async (e) => { e.preventDefault(); const r = await fetch(`${API}/profile`, { method: "PATCH", headers: headers(), body: JSON.stringify({ name }) }); if (r.ok) { updateProfile({ ...profile, name }); setNotice("Profile updated."); } }; return <section className="module-shell"><div className="module-heading"><p className="eyebrow">SYSTEM SETTINGS</p><h1>Make it <em>yours.</em></h1></div><form className="module-card settings-form" onSubmit={save}><h2>Profile</h2><label>DISPLAY NAME<input value={name} onChange={(e) => setName(e.target.value)} required /></label><label>ACCOUNT EMAIL<input value={profile?.email || ""} disabled /></label><p>Google OAuth can be enabled once your Google Client ID and secret are added to the backend environment.</p><button className="primary-button">SAVE CHANGES <span>→</span></button></form></section>; }
