import { useState } from "react";
import NeuralCore from "../components/NeuralCore";
const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";
export default function Login({ onAuthenticated }) {
  const [isRegistering, setIsRegistering] = useState(false); const [form, setForm] = useState({ name: "", email: "", password: "", confirmPassword: "" }); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
  const update = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const submit = async (e) => { e.preventDefault(); if (isRegistering && form.password !== form.confirmPassword) return setNotice("Passwords do not match."); setLoading(true); setNotice(""); try { const response = await fetch(`${API_URL}${isRegistering ? "/register" : "/login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(isRegistering ? { name: form.name, email: form.email, password: form.password } : { email: form.email, password: form.password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Unable to access BrainOS."); localStorage.setItem("brainos_token", data.access_token); onAuthenticated(); } catch (error) { setNotice(error.message === "Failed to fetch" ? "Neural gateway is offline. Start the FastAPI server first." : error.message); } finally { setLoading(false); } };
  return <main className="auth-shell"><div className="star-field" /><div className="aurora aurora-one" /><div className="aurora aurora-two" />
    <section className="auth-intro"><div className="wordmark"><i /> BRAİN<span>OS</span></div><div className="intro-orbit"><NeuralCore /></div><p className="eyebrow">COGNITIVE ALARM PLATFORM</p><h1>Wake with<br /><em>intention.</em></h1><p className="intro-copy">Your sleep rhythm, focus reserve, and morning mission — orchestrated in one calm neural space.</p><div className="signal-row"><b /> NEURAL LINK SECURE <span>v.01</span></div></section>
    <section className="auth-panel"><div className="panel-cap"><span>{isRegistering ? "NEW NEURAL PROFILE" : "IDENTITY VERIFICATION"}</span><b>01 / 01</b></div><h2>{isRegistering ? "Start your signal." : "Welcome back."}</h2><p className="panel-subtitle">{isRegistering ? "Build a more intentional morning, one cycle at a time." : "Your cognitive command center is ready."}</p><button className="google-button" onClick={() => window.location.assign(`${API_URL}/oauth/google`)} type="button"><strong>G</strong> Continue with Google <span>↗</span></button><div className="auth-divider"><span>OR CONTINUE WITH EMAIL</span></div>
      <form onSubmit={submit}>{isRegistering && <label>FULL NAME<input name="name" value={form.name} onChange={update} placeholder="Your name" required /></label>}<label>EMAIL ADDRESS<input type="email" name="email" value={form.email} onChange={update} placeholder="you@example.com" required /></label><label>PASSWORD<input type="password" name="password" value={form.password} onChange={update} placeholder="••••••••" minLength="8" required /></label>{isRegistering && <label>CONFIRM PASSWORD<input type="password" name="confirmPassword" value={form.confirmPassword} onChange={update} placeholder="••••••••" minLength="8" required /></label>}{notice && <p className="form-notice">{notice}</p>}<button className="primary-button" disabled={loading}>{loading ? "CONNECTING..." : isRegistering ? "CREATE NEURAL ID" : "ENTER BRAINOS"}<span>→</span></button></form><p className="switch-auth">{isRegistering ? "Already calibrated?" : "New to the system?"} <button type="button" onClick={() => { setIsRegistering(!isRegistering); setNotice(""); }}>{isRegistering ? "Sign in" : "Create an account"}</button></p></section>
  </main>;
}
